"""empty message

Revision ID: e0f8308a2727
Revises: 13a2768584bc
Create Date: 2024-09-01 00:33:56.887355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0f8308a2727'
down_revision = '13a2768584bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('write_comments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('write_comments', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
